### ISSUE TITLE
HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by hharmuth** [fantasydatapros/nflfastpy#6]
Seems to be a source error when calling nflfastpy.load_pbp_data and nflfastpy.load_roster_data
![404_Error](https://user-images.githubusercontent.com/61815430/185472116-0678a8c6-5de1-4338-b5f1-480fd6c7205b.png)
a

**Comment by bendominguez0111** [comment]
They've changed the source recently for nflfastR. I recommend using nfl-data-py now as it accomplishes the same thing this package used to and is just as straightforward to use. This package will be archived.
